const products=[
{id:'sausage',name:'Sausage',cat:'Extras',emoji:'🌭',options:[['1 pack',20]]},
{id:'gizzard',name:'Gizzard',cat:'Extras',emoji:'🍗',options:[['1 pack',40]]},
{id:'thighs',name:'Chicken Thighs',cat:'Chicken',emoji:'🍗',options:[['Small',30],['Medium',40],['Large',50],['X-Large',60]]},
{id:'drumsticks',name:'Chicken Drumsticks',cat:'Chicken',emoji:'🍗',options:[['5 pcs',45],['7 pcs',60],['10 pcs',90],['12 pcs',100],['15 pcs',130],['20 pcs',160]]},
{id:'back',name:'Chicken Back',cat:'Chicken',emoji:'🦴',options:[['4 pcs',20],['6 pcs',30],['8 pcs',40],['10 pcs',50]]},
{id:'tilapia',name:'Fresh Tilapia',cat:'Fish',emoji:'🐟',options:[['2 pcs',50],['3 pcs',60]]},
{id:'breast',name:'Chicken Breast',cat:'Chicken',emoji:'🍗',options:[['3 pcs',60]]}
];
const fixedBoxes=[
{id:'classic',name:'Classic Combo',items:['1 pack sausage','3 pcs chicken breast','2 pcs tilapia','5 pcs chicken back','5 pcs drumsticks'],price:170},
{id:'deluxe',name:'Deluxe Combo',items:['Classic Combo','1 pack gizzard'],price:210}
];
let cart=JSON.parse(localStorage.getItem('fc_cart')||'[]');
const $=s=>document.querySelector(s); const money=n=>`GH₵${Number(n).toFixed(0)}`;
function save(){localStorage.setItem('fc_cart',JSON.stringify(cart));renderCart()}
function add(item){const x=cart.find(i=>i.key===item.key); if(x)x.qty++; else cart.push({...item,qty:1}); save(); openCart()}
function renderProducts(cat='all'){const root=$('#products'); root.innerHTML=products.filter(p=>cat==='all'||p.cat===cat).map(p=>`<article class="card"><div class="product-img">${p.emoji}</div><h3>${p.name}</h3><div class="cat">${p.cat}</div><select data-prod="${p.id}">${p.options.map((o,i)=>`<option value="${i}">${o[0]} — ${money(o[1])}</option>`).join('')}</select><div class="price-row"><span class="price" data-price="${p.id}">${money(p.options[0][1])}</span></div><button class="btn primary add-product" data-id="${p.id}">Add to cart</button></article>`).join(''); root.querySelectorAll('select').forEach(s=>s.onchange=()=>{const p=products.find(x=>x.id===s.dataset.prod);s.closest('.card').querySelector('.price').textContent=money(p.options[s.value][1])}); root.querySelectorAll('.add-product').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.id),sel=b.closest('.card').querySelector('select'),o=p.options[sel.value];add({key:p.id+'-'+o[0],name:p.name,option:o[0],price:o[1]})})}
function renderBuilder(){const root=$('#builderItems'); root.innerHTML=products.map(p=>`<div class="builder-item"><div><b>${p.name}</b><div class="cat">Choose an option</div></div><select data-builder="${p.id}">${p.options.map((o,i)=>`<option value="${i}">${o[0]} — ${money(o[1])}</option>`).join('')}<option value="-1">Don't add</option></select></div>`).join('');root.querySelectorAll('select').forEach(s=>s.onchange=updateBox);updateBox()}
function boxItems(){return [...document.querySelectorAll('[data-builder]')].filter(s=>s.value!=='-1').map(s=>{const p=products.find(x=>x.id===s.dataset.builder),o=p.options[s.value];return {name:p.name,option:o[0],price:o[1]}})}
function updateBox(){const items=boxItems(),original=items.reduce((a,x)=>a+x.price,0),discount=original?10:0;$('#boxOriginal').textContent=money(original);$('#boxDiscount').textContent=`- ${money(discount)}`;$('#boxTotal').textContent=money(Math.max(0,original-discount));window._box={items,original,discount,total:Math.max(0,original-discount)}}
function renderFixedBoxes(){ $('#fixedBoxes').innerHTML=fixedBoxes.map(b=>`<article class="card"><div class="product-img">📦</div><span class="eyebrow">FRESH BOX</span><h3>${b.name}</h3><ul>${b.items.map(i=>`<li>${i}</li>`).join('')}</ul><div class="price-row"><span class="price">${money(b.price)}</span><button class="btn primary add-fixed" data-id="${b.id}">Add box</button></div></article>`).join('');$('#fixedBoxes').querySelectorAll('.add-fixed').forEach(btn=>btn.onclick=()=>{const b=fixedBoxes.find(x=>x.id===btn.dataset.id);add({key:b.id,name:b.name,option:'Fixed Combo',price:b.price})})}
function renderCart(){const root=$('#cartItems');$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);const total=cart.reduce((a,x)=>a+x.price*x.qty,0);$('#cartTotal').textContent=money(total);root.className='drawer-body';root.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div><b>${x.name}</b><div class="cat">${x.option}</div><div class="price">${money(x.price*x.qty)}</div></div><div class="qty"><button data-dec="${i}">−</button><b>${x.qty}</b><button data-inc="${i}">+</button><button data-del="${i}">×</button></div></div>`).join(''):`<div style="padding:30px;text-align:center;color:#746c68">Your cart is empty 🛒</div>`;root.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{cart[b.dataset.inc].qty++;save()});root.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{cart[b.dataset.dec].qty=Math.max(0,cart[b.dataset.dec].qty-1);cart=cart.filter(x=>x.qty);save()});root.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{cart.splice(b.dataset.del,1);save()})}
function openCart(){ $('#cartPanel').classList.add('open');$('#backdrop').classList.add('show') } function closeCart(){ $('#cartPanel').classList.remove('open');$('#backdrop').classList.remove('show') }
function openCheckout(){if(!cart.length)return alert('Add something to your cart first.');closeCart();$('#checkoutTotal').textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0)+5);$('#checkoutModal').classList.add('show')}
function updateDelivery(){const scheduled=document.querySelector('input[name="delivery"]:checked').value==='scheduled';$('#scheduleFields').classList.toggle('hidden',!scheduled);if(scheduled){document.querySelector('input[name="payment"][value="after"]').checked=true;$('#paymentNote').innerHTML='Scheduled delivery orders are placed first and paid after placing the order. MTN MoMo: <b>0547864825</b> — Faith Kwasi Nyarko'}else{$('#paymentNote').innerHTML='MTN MoMo: <b>0547864825</b> — Faith Kwasi Nyarko'}}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.cat)});$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#backdrop').onclick=closeCart;$('#checkoutBtn').onclick=openCheckout;$('#closeCheckout').onclick=()=>$('#checkoutModal').classList.remove('show');document.querySelectorAll('input[name="delivery"]').forEach(r=>r.onchange=updateDelivery);$('#addBox').onclick=()=>{const b=window._box;if(!b.items.length)return alert('Select at least one product.');add({key:'custom-'+Date.now(),name:'Custom Fresh Box',option:`${b.items.length} selected items`,price:b.total})};
$('#checkoutForm').onsubmit=e=>{e.preventDefault();const scheduled=document.querySelector('input[name="delivery"]:checked').value==='scheduled',payment=document.querySelector('input[name="payment"]:checked').value;const subtotal=cart.reduce((a,x)=>a+x.price*x.qty,0),deliveryFee=5,total=subtotal+deliveryFee;const id='FC-'+String((Number(localStorage.getItem('fc_order_seq')||0)+1)).padStart(5,'0');localStorage.setItem('fc_order_seq',Number(id.slice(3)));const order={id,name:$('#name').value,phone:$('#phone').value,location:$('#location').value,landmark:$('#landmark').value,delivery:scheduled?'scheduled':'same-day',date:scheduled?$('#date').value:null,time:scheduled?$('#time').value:null,payment:scheduled?'after':payment,total,items:cart,createdAt:new Date().toISOString()};localStorage.setItem('fc_last_order',JSON.stringify(order));cart=[];save();$('#checkoutModal').classList.remove('show');$('#successTitle').textContent=`Order ${id}`;$('#successText').textContent=scheduled?`Your scheduled order is placed for ${order.date} at ${order.time}. Payment is due after placing the order.`:`Your order has been received for same-day delivery. Total: ${money(total)}.`;const msg=encodeURIComponent(`Fresh Chicken Order ${id}\nName: ${order.name}\nPhone: ${order.phone}\nLocation: ${order.location}\nDelivery: ${order.delivery}${scheduled?' '+order.date+' '+order.time:''}\nTotal: ${money(total)}\nPayment: ${order.payment}`);$('#waLink').href=`https://wa.me/233552509943?text=${msg}`;$('#successModal').classList.add('show')};$('#doneBtn').onclick=()=>$('#successModal').classList.remove('show');
renderProducts();renderBuilder();renderFixedBoxes();renderCart();
